[env]
TERM = "xterm-256color"

[shell]
program = "/bin/zsh"
args = ["-l"]

[window]
dynamic_padding = true
opacity = 0.9
option_as_alt = "Both"

[font]
size = 14
normal = { family = "Hack Nerd Font", style = "Regular" }
italic = { family = "Hack Nerd Font", style = "Italic" }
bold = { family = "Hack Nerd Font", style = "Bold" }
bold_italic = { family = "Hack Nerd Font", style = "Bold Italic" }
